author: "Jorge Moura"
author_url: http://www.jjorgemoura.com
copyright: Copyright © 2018 Jorge Moura
readme: README.md

github_url: https://github.com/jjorgemoura/moviz
github_file_prefix: https://github.com/jjorgemoura/moviz/tree/master

# root_url:
docset_icon: fastlane/resources/docset-icon@2x.png

output: docs
theme: apple

sdk: iphoneos
swift-version: 4.0
source-directory: moviz/
clean: true

hide_documentation_coverage: false
skip-undocumented: false
min_acl: "internal"

xcodebuild_arguments:
    - "-project"
    - "moviz.xcodeproj"
    - "-scheme"
    - "moviz"
