
# disabled_rules:

opt_in_rules:
 - array_init
 - attributes
 - closure_end_indentation
 - closure_spacing
 - conditional_returns_on_newline
 - contains_over_first_not_nil
 - empty_count
 - explicit_enum_raw_value
 - explicit_init
 - explicit_type_interface
 - extension_access_modifier
 - fatal_error_message
 # - file_header
 - first_where
 - force_unwrapping
 - implicit_return
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - let_var_whitespace
 - literal_expression_end_indentation
 - multiline_arguments
 - multiline_parameters
 - nimble_operator
 - no_extension_access_modifier
 - no_grouping_extension
 - number_separator
 - object_literal
 - operator_usage_whitespace
 - overridden_super_call
 - pattern_matching_keywords
 - private_outlet
 - prohibited_super_call
 - quick_discouraged_call
 - redundant_nil_coalescing
 - single_test_class
 - sorted_imports
 - strict_fileprivate
 - switch_case_on_newline
 - trailing_closure
 - unneeded_parentheses_in_closure_argument
 - vertical_parameter_alignment_on_call

excluded:
  - Pods
  - Carthage

line_length: 200
file_length:
  warning: 280
  error: 480
identifier_name:
  excluded:
    - T
    - URL
type_name:
  excluded:
    - T

# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/  .*?\.swift
#                     \/\/  toscoz
#                     \/\/
#                     \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
#                     \/\/  Copyright © \d{4} Jorge Moura\. All rights reserved\.
#                     \/\/
