# notification options
notifications:
  email: false
  slack:
    rooms:
      secure: Au0K922OZijH3BHVMrasF4sYp6BCWtbRYyI60tnFx6SCjnDMmZfDjIFRwlrLqbe/GUcWludUICHUpwlztsErGJkvm4Xw3JLeqgNQE8pbwXku9kdDiqXLIZNdRT6GmnEEITChrwiRmHYtTS3wcQbapFk1rLWR+8leIn8ow3+zIWnla3aZ5UTWHgU+k1HZNFRcgpoH8y4uKKPQ3XPXrhwkEpbB3ywmiYZgUsPpvqMq7NeJASGHoqLxKiNkLqyKIeyvT+7boEM3smbg0mzc+uC0SFVP6BZ1rfAVjFag8pK01UVctQhfxtFgaM/KbipJcTvqoOwxxz4XRYfZBlFQeEElqtA63TiNMOlHcDdYUJABszUyxA1/3NjSN/WwczFRAN7bCFUYE/NDMMbbeptapdjfGRgBa7EsMFES2tUpicDO4cZNZg19Ymjut5BVTto2luov7FPKbefQJcOxynoS+e5+I8w4qoAlRgOdgyBBIP1BA2vDvs9ECvXp+6wJb++lVyTibrQozdhCN2Lk3dSo2gCJjc94zuHnsm1girhZuRQbJmaHorQ+y0DYCsNgpVrgugMbPai0C/RY7oBunvcrYskQXClqWMM1mB3g4z5ALTeK0rNlxkKEwH8G4idUjRN/3afWaAP9RpM3EQPon60msuhMsTufmXLafX5twTYki8OoB08=
    on_success: always
    on_failure: always


# language
language: objective-c

# language options
osx_image: xcode9.2

# branches to run


# environment variables
env:
  # global: the same across all matrix possibilities
  global:
    - LANG=en_US.UTF-8

    - PROJECT="moviz.xcodeproj"
    - IOS_SCHEME="moviz"

    - IOS_SDK=iphonesimulator11.2

  # matrix: a new build for each specified variable
  matrix:
    - DESTINATION="OS=11.2,name=iPhone X"                               SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"
    - DESTINATION="OS=11.2,name=iPad Pro (10.5-inch)"                   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"


####################
## begin build steps

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - fastlane update_fastlane

before_script:
  - carthage bootstrap --platform iOS

script:
- xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration Debug -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
# - fastlane do_ui_tests

after_success:
- bash <(curl -s https://codecov.io/bash) -J 'moviz'


####################
## Deployment options
